### ISSUE TITLE
AttributeError: 'function' object has no attribute 'func_code'

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/mpi4pyscf#3]
I ran the 01-parallel_krhf-diamond.py example and got this error:

> Traceback (most recent call last):
>   File "01-parallel_krhf-diamond.py", line 34, in <module>
>     mf.with_df = df.FFTDF(cell, kpts)
>   File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi.py", line 498, in init
>     (args[0].dumps(),)+args[1:], kwargs))
>   File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi_pool.py", line 133, in apply
>     F = _function_wrapper(function)
>   File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi_pool.py", line 171, in __init__
>     self.func_code = marshal.dumps(function.func_code)
> AttributeError: 'function' object has no attribute 'func_code'

**Comment by sunqm** [comment]
This is a python 3 compatibility issue.  The attribute .func_code of python2 was replaced by python 3 .__code__ attribute.

**Comment by danielsjf** [comment]
.__code__ to be precise

**Comment by RiaanLab** [comment]
@danielsjf  Thanks, there is a huge difference between the two.

**Comment by babaralishah** [comment]
Hi!

HEre is my code and error below:
please assist...
![image](https://user-images.githubusercontent.com/37935603/152304488-fdbb6fa5-9465-48bc-947b-ae4915e57f07.png)
